export const EVENT_ROLE_MAP = {
  ORDER_CONFIRMED: ["MANAGER", "SALES_OFFICER","SALES OFFICER","SALES_OFFICER_VNR","SALES OFFICER VNR", "DISTRIBUTOR", "DRIVER"],
  SLOT_BOOKING_COMPLETED: ["MANAGER", "SALES_OFFICER","SALES OFFICER","SALES_OFFICER_VNR","SALES OFFICER VNR", "DISTRIBUTOR"],
  DELIVERY_COMPLETED: ["SALES_OFFICER","SALES OFFICER","SALES_OFFICER_VNR","SALES OFFICER VNR", "DISTRIBUTOR","MANAGER"],
  DRIVER_ASSIGNED: ["DRIVER"],
  DRIVE_STARTED: ["DRIVER", "DISTRIBUTOR"],
  REACHED_D1:["DISTRIBUTOR"],
  REACHED_D2:["DISTRIBUTOR"],
};
